version: "3.9"

services:
  db-sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - pgdata:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3

  backend-dj:
    container_name: "cma-backend"
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-sqlite

  frontend-vite:
    container_name: "cma-frontend"
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-dj

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-vite
      - backend-dj

volumes:
  pgdata: {}
