# Generated by Django 4.2.15 on 2024-08-31 12:24

from django.db import migrations
import random

def create_dummy_vehicles(apps, schema_editor):
    Vehicle = apps.get_model('vehicles', 'Vehicle')

    makes_and_models = [
        ("Toyota", "Camry"),
        ("Honda", "Civic"),
        ("Ford", "Mustang"),
        ("Chevrolet", "Malibu"),
        ("Nissan", "Altima"),
        ("BMW", "3 Series"),
        ("Audi", "A4"),
        ("Mercedes-Benz", "C-Class"),
        ("Tesla", "Model 3"),
        ("Hyundai", "Elantra")
    ]

    vehicles = []
    for i in range(50):
        make, model = random.choice(makes_and_models)
        year = random.randint(2015, 2022)
        vin = f"VIN{str(i + 1).zfill(3)}"
        mileage = random.randint(1000, 20000)

        vehicles.append(Vehicle(
            make=make,
            model=model,
            year=year,
            vin=vin,
            mileage=mileage,
        ))

    Vehicle.objects.bulk_create(vehicles)

class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_vehicles),
    ]